//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.27 at 04:57:17 PM CEST 
//


package dinos.storagetypes;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dataStream.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dataStream">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="network"/>
 *     &lt;enumeration value="memory"/>
 *     &lt;enumeration value="storage"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "dataStream")
@XmlEnum
public enum DataStream {

    @XmlEnumValue("network")
    NETWORK("network"),
    @XmlEnumValue("memory")
    MEMORY("memory"),
    @XmlEnumValue("storage")
    STORAGE("storage");
    private final String value;

    DataStream(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DataStream fromValue(String v) {
        for (DataStream c: DataStream.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
