//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.27 at 04:57:17 PM CEST 
//


package dinos.storagetypes;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dataType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dataType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="raw"/>
 *     &lt;enumeration value="hardware"/>
 *     &lt;enumeration value="metadata"/>
 *     &lt;enumeration value="configuration"/>
 *     &lt;enumeration value="communication"/>
 *     &lt;enumeration value="process"/>
 *     &lt;enumeration value="session"/>
 *     &lt;enumeration value="user"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "dataType")
@XmlEnum
public enum DataType {

    @XmlEnumValue("raw")
    RAW("raw"),
    @XmlEnumValue("hardware")
    HARDWARE("hardware"),
    @XmlEnumValue("metadata")
    METADATA("metadata"),
    @XmlEnumValue("configuration")
    CONFIGURATION("configuration"),
    @XmlEnumValue("communication")
    COMMUNICATION("communication"),
    @XmlEnumValue("process")
    PROCESS("process"),
    @XmlEnumValue("session")
    SESSION("session"),
    @XmlEnumValue("user")
    USER("user");
    private final String value;

    DataType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DataType fromValue(String v) {
        for (DataType c: DataType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
