//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.27 at 05:57:46 PM CEST
//


package dinos.storagetypes;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the generated package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReportBundle_QNAME = new QName("", "reportBundle");
    private final static QName _ObservationReport_QNAME = new QName("", "observationReport");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReportBundle }
     *
     */
    public ReportBundle createReportBundle() {
        return new ReportBundle();
    }

    /**
     * Create an instance of {@link ObservationReport }
     *
     */
    public ObservationReport createObservationReport() {
        return new ObservationReport();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReportBundle }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "reportBundle")
    public JAXBElement<ReportBundle> createReportBundle(ReportBundle value) {
        return new JAXBElement<ReportBundle>(_ReportBundle_QNAME, ReportBundle.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObservationReport }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "observationReport")
    public JAXBElement<ObservationReport> createObservationReport(ObservationReport value) {
        return new JAXBElement<ObservationReport>(_ObservationReport_QNAME, ObservationReport.class, null, value);
    }

}