//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.27 at 04:57:17 PM CEST 
//


package dinos.storagetypes;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Wraps the output of an analysis tool with relevant metadata.
 * 
 * <p>Java class for ObservationReport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObservationReport">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="observationData" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="storageTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="tool" type="{}tool" />
 *       &lt;attribute name="dataStream" type="{}dataStream" />
 *       &lt;attribute name="dataType" type="{}dataType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObservationReport")
public class ObservationReport {

    @XmlAttribute(name = "observationData")
    protected String observationData;
    @XmlAttribute(name = "storageTimestamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar storageTimestamp;
    @XmlAttribute(name = "tool")
    protected Tool tool;
    @XmlAttribute(name = "dataStream")
    protected DataStream dataStream;
    @XmlAttribute(name = "dataType")
    protected DataType dataType;

    /**
     * Gets the value of the observationData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservationData() {
        return observationData;
    }

    /**
     * Sets the value of the observationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservationData(String value) {
        this.observationData = value;
    }

    /**
     * Gets the value of the storageTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStorageTimestamp() {
        return storageTimestamp;
    }

    /**
     * Sets the value of the storageTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStorageTimestamp(XMLGregorianCalendar value) {
        this.storageTimestamp = value;
    }

    /**
     * Gets the value of the tool property.
     * 
     * @return
     *     possible object is
     *     {@link Tool }
     *     
     */
    public Tool getTool() {
        return tool;
    }

    /**
     * Sets the value of the tool property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tool }
     *     
     */
    public void setTool(Tool value) {
        this.tool = value;
    }

    /**
     * Gets the value of the dataStream property.
     * 
     * @return
     *     possible object is
     *     {@link DataStream }
     *     
     */
    public DataStream getDataStream() {
        return dataStream;
    }

    /**
     * Sets the value of the dataStream property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataStream }
     *     
     */
    public void setDataStream(DataStream value) {
        this.dataStream = value;
    }

    /**
     * Gets the value of the dataType property.
     * 
     * @return
     *     possible object is
     *     {@link DataType }
     *     
     */
    public DataType getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataType }
     *     
     */
    public void setDataType(DataType value) {
        this.dataType = value;
    }

}
